name: BizBrad
favicon: null
layout_spectrum: 0.75515
typography_spectrum: 0.74737
title: Writing code. Solving problems.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5a5b5f'
    - '#86cef8'
    - '#1484bf'
    - '#083ab8'
  brandStrength: 0.6452492114622146
  lightness: 0.8562906414736062
  saturation: 0.9380341700743884
  rhythmicContrast: 0.9350883245933801
purpose: []
